server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root /usr/share/ldap-account-manager;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass unix:/run/php/php8.4-fpm.sock;
    }

    location ~ ^/(config|lib|help|locale|sess|tmp|docs)/(?:.*)$ {
        deny all;
        return 403;
    }
}