---
openldap_config_user: openldap
openldap_config_service_name: openldap
openldap_config_base_dn: dc=embtom,dc=org
openldap_config_organization: embtom
openldap_config_tls_enabled: true
openldap_config_schemas: []
openldap_config_organizational_units:
  - People
  - Groups
  - Services
  - Computers
  - Samba
openldap_config_indexes:
  - objectClass eq
  - cn,sn,uid eq,pres,sub
  - uidNumber,gidNumber eq
  - member,memberUid eq
  - uniqueMember eq,pres
  - loginShell eq
openldap_config_dir: /var/lib/openldap/config
openldap_config_file: "{{ openldap_config_dir }}/slapd.conf"
openldap_config_bootstrap_file: "{{ openldap_config_dir }}/bootstrap.ldif"
