---
- name: Reload OpenLDAP user systemd daemon
  become: true
  become_user: "{{ openldap_service_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ openldap_service_user_uid }}"
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true

- name: Restart OpenLDAP service
  become: true
  become_user: "{{ openldap_service_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ openldap_service_user_uid }}"
  ansible.builtin.systemd:
    name: "{{ openldap_service_name }}.service"
    scope: user
    state: restarted
