---
all:
  children:
    openldap:
      hosts:
        localhost:
          ansible_host: localhost
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3.13
        remote:
          ansible_connection: ssh
          ansible_python_interpreter: /usr/bin/python3.13
