---
openldap_service_user: "{{ openldap_config_user }}"
openldap_service_name: "{{ openldap_config_service_name }}"
openldap_service_container_method: image-pull
openldap_service_direct_build_image: localhost/openldap:trixie
openldap_service_image_pull_image: >-
  ghcr.io/embtom/openldap-infra/openldap:{{
  openldap_infra_image_tag | default('latest') }}
openldap_service_image: >-
  {{ openldap_service_direct_build_image
     if openldap_service_container_method == 'direct-build'
     else openldap_service_image_pull_image }}
openldap_service_containerfile: container/openldap/Containerfile
openldap_service_build_context: .
openldap_service_build_extra_args: ""
openldap_service_force_rebuild: false
openldap_service_data_dir: /var/lib/openldap/data
openldap_service_data_recreate: false
openldap_service_full_recreate: false
openldap_service_unprivileged_port_start: 389
openldap_service_ldap_port: 389
openldap_service_ldaps_port: 636
openldap_service_tls_enabled: "{{ openldap_config_tls_enabled }}"
openldap_service_tls_dir: /var/lib/openldap/tls
openldap_service_tls_server_name: "{{ openldap_external_host }}"
openldap_service_tls_certificate_name: >-
  {{ openldap_service_tls_server_name }}-{{ openldap_service_name }}
