---
openldap_service_user: "{{ openldap_config_user }}"
openldap_service_name: "{{ openldap_config_service_name }}"
openldap_service_container_method: direct-build
openldap_service_image: localhost/openldap:trixie
openldap_service_containerfile: container/Containerfile
openldap_service_build_context: .
openldap_service_build_extra_args: ""
openldap_service_force_rebuild: false
openldap_service_data_dir: /var/lib/openldap/data
openldap_service_schema_dir: /var/lib/openldap/schema
openldap_service_unprivileged_port_start: 389
openldap_service_ldap_port: 389
openldap_service_ldaps_port: 636
openldap_service_tls_enabled: "{{ openldap_config_tls_enabled }}"
openldap_service_tls_cert_file: /var/lib/openldap/tls/tls.crt
openldap_service_tls_key_file: /var/lib/openldap/tls/tls.key
