---
ldap_account_manager_enabled: true
ldap_account_manager_user: "{{ openldap_service_user }}"
ldap_account_manager_service_name: ldap-account-manager
ldap_account_manager_image: localhost/ldap-account-manager:trixie
ldap_account_manager_containerfile: container/ldap-account-manager/Containerfile
ldap_account_manager_build_context: .
ldap_account_manager_build_extra_args: ""
ldap_account_manager_force_rebuild: false
ldap_account_manager_config_dir: /var/lib/ldap-account-manager/config
ldap_account_manager_data_dir: /var/lib/ldap-account-manager/data
ldap_account_manager_port: 8082
ldap_account_manager_profile_name: openldap
ldap_account_manager_server_url: ldap://openldap:389
ldap_account_manager_base_dn: "{{ openldap_config_base_dn }}"
