---
- name: Include OpenLDAP configuration setup tasks
  ansible.builtin.include_tasks: setup.yml

- name: Include rendered OpenLDAP configuration tasks
  ansible.builtin.include_tasks: configuration.yml

- name: Include OpenLDAP schema deployment tasks
  ansible.builtin.include_tasks: schemas.yml
