---
sssd_client_ldap_host: ""
sssd_client_ldap_uri: "ldaps://{{ sssd_client_ldap_host }}"
sssd_client_search_base: "{{ openldap_config_base_dn }}"
sssd_client_bind_dn: >-
  cn={{ openldap_config_services.bind_cn }},ou=Services,
  {{ openldap_config_base_dn }}
sssd_client_bind_password: >-
  {{ openldap_config_services.bind_password }}
sssd_client_ca_certificate: >-
  /usr/local/share/ca-certificates/openldap-root-ca.crt
sssd_client_mkhomedir_enabled: true
sssd_client_packages:
  - ca-certificates
  - libnss-sss
  - libpam-mkhomedir
  - libpam-sss
  - sssd
  - sssd-ldap
